### ISSUE TITLE
Update the Profile page - To display profile pic of standard fixed size.

### ISSUE THREAD

**Issue by bikirandas** [bikirandas/OmexOnline#3]
Update Requirements:
1. User may upload profile pic of any size - process the image to standard size for display.
2. Retain the actual pic uploaded and Display the Actual size pic when clicked on the profile pic present on the webpage.
3. Develop a image processing feature for the above.

**Comment by bikirandas** [comment]
@sudheersingampalli -- 

Hi Sudheer - Do pass your suggestions over this comment for this modification. If there is any other feature you were working on we can integrate both applications into one. Please do suggest.

**Comment by bikirandas** [comment]
Profile Page upgradation started.

**Comment by bikirandas** [comment]
de011b7 - includes the profile image to be displayed in a round frame and display first_name of the user

**Comment by bikirandas** [comment]
**Tested the commits** 
61dba1c
de011b7 
8ea0cbf
f58e7ef

**Issues registered -** 

1.  Profile pic fit on the round frame is not proper - _Analysing resolution approach_
2.  Profile container window fit to be adjusted  for various screen size. - _Analysis on Hold_

**Comment by bikirandas** [comment]
For proper sizing of profile pic the pic need to be modified during the upload process

_Analysing ways to process uploaded pics in the Django application server to convert them to required size._

**Comment by bikirandas** [comment]
profile card - background image resized with the commit 
82aecdb

**Comment by bikirandas** [comment]
Setup profile page such that user can select custom background image - for their individual profile self display

**Comment by bikirandas** [comment]
For the custom Coverpic of each profile update the Accounts/models.py with coverpic column and upload folder  -- users/%username/cover

**Comment by bikirandas** [comment]
checking for pic upload widget in Django

**Comment by bikiransv** [comment]
Using Pyuploadcare module for cover pic selection feature so that the Image upload can be more attractive with cropping and drag-drop features 

**Issues Encountered after Pyuploadcare implementation**

1. cover pic  Upload option is not visible from the website, where as the options is working from the admin interface.

**Comment by bikiransv** [comment]
Modify the User Edit page to have the cover image upload option more interactive.

**Comment by bikirandas** [comment]
Issue #3 - Coverpic Display issue Fixed.

**Comment by bikirandas** [comment]
Issue #3 - Update UI for Profile view and edit pages.
Feature To be added in 0.0.11c Version.

1. Enable User to Post in Profile Page.

**Comment by bikirandas** [comment]
Issue #3 - Update UI for Profile view and edit pages.
Feature To be added in 0.0.11c Version.

Enable User to Post in Profile Page. ----> All commits for this purpose should be marked with 0.0.11c release tag

**Comment by bikirandas** [comment]
Issue Closed as too many features are handeled in the same issue. Most of the Profile pic and cover pic display issu is resolved.
